packages:
  - apps/**
  - packages/**

catalog:
  typescript: 5.9.2
  "@trpc/client": 11.5.0
  "@trpc/server": 11.5.0
  "@trpc/tanstack-react-query": 11.5.0
  "@tanstack/react-query": 5.90.1
  "@types/node": 22.15.34
  react: 19.1.0

overrides:
  react: 19.1.0
